import Head from "next/head";
import Image from "next/image";
import NavHeader from "@/components/navigation/NavHeader";

export default function Home() {
	return (
		<>
			<Head>
				<title>OVRA</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<NavHeader />
				{/* Hero */}
				<section className="flex justify-center items-center gap-x-24 mt-20">
					<div>
						<h1 className="text-8xl font-bold">OVRA</h1>
						<h2 className="text-4xl">The next step in virtual reality</h2>
						<div className="text-lg w-96 pt-4">
							The Ontario Virtual Reality Association (OVRA) is a non-profit
							organization that promotes the use of virtual reality (VR)
							technology in Ontario, Canada.
						</div>
						<div className="flex gap-x-4 mt-4">
							<button className="bg-white text-black font-bold py-2 px-10 rounded">
								Learn more
							</button>
							<button className="bg-white text-black font-bold py-2 px-10 rounded">
								Contact us
							</button>
						</div>
					</div>
					<div>
						<Image
							src="/landing/hero.png"
							alt="OVRA Logo"
							width={500}
							height={100}
						/>
					</div>
				</section>
			</main>
		</>
	);
}
